boom_saloon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import include, path, reverse_lazy
from home import views
from django.contrib.auth import views as auth_views



app_name = 'home'

urlpatterns = [
    path('', views.home, name="home"),
    path('login/', views.user_login, name="login"),
    path('myprofile/', views.my_profile, name="myprofile"),
    path('signup/', views.user_signup, name="signup"),
    path('<int:id>/', views.magazine, name="magazine"),
    path('<int:id>/<slug:slug>/', views.issue, name="issue"),
    path('contact/', views.contact, name="contact"),
    path('mymagazines/', views.mymags, name="mymagazines"),
    path('signout/', views.user_signout, name="signout"),
    path('saveissue/', views.save_issue, name="save-issue"),
    path('membership/', views.membership, name="membership"),
    path('staff/', views.staff, name="staff"),
    path('codes/', views.codes, name='codes'),
    path('password_reset/done/', views.password_reset_done, name='password_reset_done'),
    path("password_reset", views.password_reset_request, name="password_reset"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="resetpassword/password_reset_confirm.html", success_url=reverse_lazy(
        'home:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', views.password_reset_complete, name='password_reset_complete'),
    path('email/', views.send_code, name="sendcode"),
    path('payment-done/', views.payment_done, name='payment_done'),
    path('payment-cancelled/', views.payment_cancelled, name='payment_cancelled'),
    path('confirm_email/<uidb64>/<token>/', views.confirm_email, name='activate'),
    path('verify_email/', views.send_confirmation_email, name="sendvemail"),

]

home/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.core.validators import MinLengthValidator
from django.contrib.auth.models import User
import datetime
import dateutil.relativedelta as dt



class Magazine(models.Model):

    id = models.IntegerField(unique=True, primary_key=True)
    title = models.CharField(max_length=100, unique=True)
    description_short = models.CharField(max_length=1000)
    #long - in case we have seperate pages for each magzine
    description_long = models.CharField(max_length=2000)
    link_to_publishers_site = models.URLField(max_length=300)
    #slug - again, in case we have seperate pages for each magzine
    slug = models.SlugField(unique=True)
    mag_cover = models.ImageField(upload_to='mag_covers', default=None)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Magazine, self).save(*args, **kwargs)


class MagazineIssue (models.Model):
    magazine = models.ForeignKey(Magazine, on_delete=models.CASCADE)
    title = models.CharField(max_length =1000, default="No title", unique=True)
    issue_description = models.CharField(max_length=1000)
    price = models.IntegerField(default = 0 )
    discounted_price = models.IntegerField(default= 0)
    cover = models.ImageField(upload_to='issue_covers', default=None)
    description_short = models.CharField(max_length=1000, default=None, null=True)
    date = models.DateField(("Date"), default=datetime.date.today)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(MagazineIssue, self).save(*args, **kwargs)


class UserProfile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    saved_issues = models.ManyToManyField(MagazineIssue, related_name="saves")
    is_subscribed = models.BooleanField(default=False)
    has_code = models.BooleanField(default=False)
    date_subscribed =  models.DateField(("Date"), default=datetime.date.today)
    email_confirmed = models.BooleanField(default=False)


    def __str__(self):
        return self.user.username


class Hashtag(models.Model):
    text = models.CharField(max_length=20)
    magazines = models.ManyToManyField(Magazine)

    def __str__(self):
        return self.text


class DiscountCode(models.Model):
    code = models.CharField(max_length=16, validators=[MinLengthValidator(16)])
    date_valid=models.DateTimeField(("Date"),default=datetime.date.today()+dt.relativedelta(months=1))
    def __str__(self):
        return self.code
        
class Membership(models.Model):
	user=models.OneToOneField(User, on_delete=models.CASCADE)
	date_subscribed= models.DateField(("Date"),default=datetime.date.today)
	date_valid=models.DateField(("Date"))
	code=models.CharField(max_length=16, validators=[MinLengthValidator(16)])

home/forms.py
from django import forms
from django.contrib.auth.models import User
from home.models import Magazine, UserProfile, MagazineIssue, Hashtag, UserProfile
from django.contrib.auth.forms import PasswordChangeForm



class UserForm(forms.ModelForm):
    email = forms.EmailField(required=True, widget=forms.widgets.TextInput(attrs={'placeholder': 'Email'}))
    username = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={'placeholder': 'Username'}))
    password = forms.CharField(required=True, min_length=8, widget=forms.widgets.PasswordInput())
    confirm_password = forms.CharField(required=True, widget=forms.widgets.PasswordInput())

    class Meta:
        model = User
        fields = ('email', 'username', 'password')

    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password = self.cleaned_data.get("password")
        confirm_password = self.cleaned_data.get("confirm_password")
        user_email = self.cleaned_data.get('email')

        if password != confirm_password:
            self.add_error("confirm_password", "Passwords do not match.")

        if User.objects.filter(email=user_email):
            self.add_error('email', 'A user with this email already exists.')

        return cleaned_data


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ()


class CodesFileForm(forms.Form):
    amount = forms.IntegerField(required=True, min_value=1, max_value=500, widget=forms.widgets.NumberInput)


class UploadCodesFileForm(forms.Form):
    file = forms.FileField(required=True)

    def clean(self):
        cleaned_data = super(UploadCodesFileForm, self).clean()
        file = cleaned_data.get('file')

        if file:
            filename = file.name
            if filename.endswith('.csv') == False:
                print('File is not a csv file as expected')
                raise forms.ValidationError("File selected is not a csv. Please ensure the correct file is selected")

        return file



class UserPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super(PasswordChangeForm, self).__init__(*args, **kwargs)

    old_password = forms.CharField(label='', widget=forms.PasswordInput(attrs={
        'placeholder': 'Old Password',
    }))

    new_password1 = forms.CharField(label='', widget=forms.PasswordInput(attrs={
        'placeholder': 'New Password',
        }))

    new_password2 = forms.CharField(label='', widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm Password',
    }))

home/views.py
from django.shortcuts import render, redirect
from django.core.mail import EmailMessage
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.forms import PasswordChangeForm, PasswordResetForm
from django.template.defaulttags import register
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse

from django.urls import reverse, reverse_lazy
from home.models import Magazine, UserProfile, Hashtag, MagazineIssue, DiscountCode, Membership
from datetime import datetime
import random, string, secrets
import dateutil.relativedelta

from home.forms import UserForm, UserProfileForm, UploadCodesFileForm, CodesFileForm, UserPasswordChangeForm
from datetime import datetime
import random, string, secrets
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes, force_text
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.sites.shortcuts import get_current_site
from home.tokens import account_activation_token
from django.contrib.auth import views as auth_views
from paypal.standard.forms import PayPalPaymentsForm
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from paypal.standard.models import ST_PP_COMPLETED
from paypal.standard.ipn.signals import valid_ipn_received
from django.dispatch import receiver
from django.views.generic import TemplateView



def is_mobile_device(request):
    # check visitor agent
    try:
        user_agent = request.META['HTTP_USER_AGENT']
    except:
        return False

    keywords = ['Mobile', 'Opera Mini', 'Android']

    if any(word in user_agent for word in keywords):
        return True
    else:
        return False


def home(request):
    ctx = {}

    ctx['magazines'] = Magazine.objects.all()

    if is_mobile_device(request):
        # mobile
        temp = 'mobiletemplates/homemobile.html'
    else:
        # desktop
        temp = 'home.html'

    return render(request, temp, context=ctx)


def user_login(request):

    if is_mobile_device(request):
        # mobile
        temp = 'mobiletemplates/login_separate_page_mobile.html'
    else:
        # desktop
        temp = "login.html"

    # if HTTP POST pull relevant info
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('home:home'))
            else:
                return HttpResponse("Your account is disabled")
        else:
            print("Invalid login details: {0}, {1}.".format(username, password))
            return HttpResponse("Invalid login details supplied.")

    return render(request, temp, {})


def user_signup(request):
    registered = False

    if is_mobile_device(request):
        # mobile
        temp = 'mobiletemplates/signupmobile.html'
    else:
        # desktop
        temp = 'signup.html'

    # if HTTP POST then process form
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        # if both forms are valid
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save(commit=False)
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()

            registered = True
            send_confirmation_email(user, request)
            user = authenticate(username=user_form.cleaned_data['username'],
                                password=user_form.cleaned_data['password'])
            login(request, user)
            return redirect(reverse('home:home'))

        else:
            print(user_form.errors, profile_form.errors)
            return render(request, temp, {'form': user_form})
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    ctx = {'user_form': user_form, 'profile_form': profile_form, 'registered': registered}

    return render(request, temp, context=ctx)

# Mobile version uses myprofile view to render as at seemed that this would require less duplicate code
# - i.e. coping the functions for several views using differnt urls on desktop but renderd all on the same page for mobile
@login_required
def my_profile(request):
    ctx = {}
    password_form = UserPasswordChangeForm(request.user, prefix='password_form')
    user = UserProfile.objects.get(user=request.user)
    issues = user.saved_issues.order_by("magazine")
    user2 = request.user

    ctx['magazines'] = Magazine.objects.all()
    ctx['savedissues'] = issues.all()
    ctx['curr_user'] = user


    if request.user.is_authenticated:
        ctx['subscribed'] = UserProfile.objects.get(user=request.user).is_subscribed
        if ctx['subscribed']==True:
            ctx['date_subscribed']=UserProfile.objects.get(user=request.user).date_subscribed
            ctx['date_valid']=Membership.objects.get(user=request.user).date_valid

    codes=DiscountCode.objects.all().count()
    ctx['codes']=codes


    if codes==0:
        ctx['countdown']="No codes left."
    elif codes==1:
        ctx['countdown']="Only 1 code left."
    else:
        ctx['countdown']="There are {} codes left.".format(codes)

    host = request.get_host()
    paypal_dict={
        'business':settings.PAYPAL_RECEIVER_EMAIL,
        'amount':5.00,
        'item_name':"Membership",
        #'invoice': DiscountCode.objects.all()[0],
        'currency_code':'GBP',
        'return_url': 'http://{}{}'.format(host, reverse('home:payment_done')),


        'cancel_return': 'http://{}{}'.format(host,
                                              reverse('home:payment_cancelled')),
            "sra": "1",                        # reattempt payment on payment error
    }
    ctx['form']=PayPalPaymentsForm(initial=paypal_dict, button_type="subscribe")


    if request.method == 'POST':
        action = request.POST['action']

        if action == 'verify_email':
            send_confirmation_email(user2, request)
            messages.success(request, 'Email Sent')
            return redirect(reverse('home:myprofile'))

        if action == 'edit_password':
            password_form = UserPasswordChangeForm(request.user, request.POST, prefix='password_form')
            if password_form.is_valid():
                user = password_form.save()
                update_session_auth_hash(request, user)
                messages.success(request, 'Password updated')
                return redirect(reverse('home:myprofile'))

    ctx['password_form'] = password_form
    
    if request.user.is_authenticated:
        ctx['subscribed'] = UserProfile.objects.get(user=request.user).is_subscribed
        if ctx['subscribed']==True:
            ctx['date_subscribed']=UserProfile.objects.get(user=request.user).date_subscribed
            ctx['date_valid']=Membership.objects.get(user=request.user).date_valid

    if is_mobile_device(request):
        # mobile
        temp = 'mobiletemplates/membershipmenumobile.html'
    else:
        # desktop
        temp = 'myprofile.html'


    return render(request, temp, ctx)


def renewMemberships(request):
    memberships=Membership.objects.all()
    if memberships.count()!=0:
        if memberships[0].date_valid < datetime.now().date():
            for membership in memberships:
                user=membership.user
                u=UserProfile.objects.get(user=user)
                u.is_subscribed=False
                u.has_code=False
                u.save()
            memberships.delete()


def membership(request):

    renewMemberships(request)

    ctx = {}
    ctx['magazines'] = Magazine.objects.all()
    

    if request.user.is_authenticated:
        ctx['subscribed'] = UserProfile.objects.get(user=request.user).is_subscribed
        ctx['email_confirmed']=UserProfile.objects.get(user=request.user).email_confirmed
        if ctx['subscribed']==True:
            ctx['date_subscribed']=UserProfile.objects.get(user=request.user).date_subscribed
            ctx['date_valid']=Membership.objects.get(user=request.user).date_valid

    codes=DiscountCode.objects.all().count()
    ctx['codes']=codes
    
    
    
    if codes==0:
        ctx['countdown']="No codes left."
    elif codes==1:
        ctx['countdown']="Only 1 code left."
    else:
        ctx['countdown']="There are {} codes left.".format(codes)
    letters=string.ascii_letters
    random_var=''.join(random.choice(letters) for i in range (20))
    
    host=request.get_host()
    paypal_dict={
        'business':settings.PAYPAL_RECEIVER_EMAIL,
        'amount':5.00,
        'item_name':"Membership",
        #'invoice': DiscountCode.objects.all()[0],
        'currency_code':'GBP',
        'return_url': 'http://{}{}'.format(host, reverse('home:payment_done')),


        'cancel_return': 'http://{}{}'.format(host,
                                              reverse('home:payment_cancelled')),
            "sra": "1",                        # reattempt payment on payment error
    }
    ctx['form']=PayPalPaymentsForm(initial=paypal_dict, button_type="subscribe")
    


    return render(request, 'membership.html', context=ctx)



@login_required
def user_signout(request):

templates/confirm_email.html
{% autoescape off %}
Hello,

Please use the link below to confirm your email:

{{ protocol }}://{{ domain }}{% url 'home:activate' uidb64=uid token=token %}

The Clò Team

{% endautoescape %}

templates/emailverifyfail.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="/static/styles/home.css">
{% endblock %}

{% block title %}
Email Verification Failed
{% endblock %}

{% block navbar %}
{% include "navbar.html" %}
{% endblock %}

{% block content %}


<!--Reset Password-->
	<div class="container p-5">
  	 	<h2 class="font-weight-bold mt-3">Email Verification Link Error</h2>
		<hr>
		<p>This link may be invalid/expired, please request a new one from the profile page.</p>
        <a href="{% url 'home:login' %}">Login</a>

  	</div>

{% endblock %}

templates/emailverifysuccess.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="/static/styles/home.css">
{% endblock %}

{% block title %}
Email Verified
{% endblock %}

{% block navbar %}
{% include "navbar.html" %}
{% endblock %}

{% block content %}


<!--Reset Password-->
	<div class="container p-5">
  	 	<h2 class="font-weight-bold mt-3">Email Verified</h2>
		<hr>
        <p>You have successfully verified your Clò email.</p>
        <a href="{% url 'home:login' %}"> Login </a>

  	</div>

{% endblock %}

templates/issue.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="/static/styles/home.css">
{% endblock %}

{% block title %}
{{this.title}}
{% endblock %}

<!--see navbar.html for navbar code-->
{% block navbar %}
{% include "navbar.html" %}
{% endblock %}

{% block content %}
<div class="container py-0 px-0 mr-0 d-inline">
    <div class="row">
        <div style="min-height: 80vh;" class="col-sm-4 pt-3 px-0">
            {% include "sidebar.html" %}
        </div>

        <div class="col-sm-4 border-start border-end border-dark border-1 d-flex" id="mainbox">
            <div class="info-box sticky-top mx-4 pe-4 d-flex">
                <div class="issues mt-4">
                    {% for issue in issues reversed %}
                        {% if issue.slug == thisIssue.slug %}
                        <a href="{% url 'home:magazine' this.id %}" class=" yellow issue-crd card issue-link py-1">
                            <img class="card-img-top" src="{{ thisIssue.cover.url }}" />
                            <div style=" display:flex; justify-content:center;" class="card-body">
                                <h5 class="sml-txt card-title">Issue {{forloop.revcounter}}: {{issue.title}}</h5>
                            </div>
                        </a>
                        {% else %}
                        <a href="{% url 'home:issue' this.id issue.slug %}" class="issue-crd card issue-link py-1">
                            <img class="card-img-top" src="{{ issue.cover.url }}" />
                            <div style=" display:flex; justify-content:center;" class="card-body">
                                <h5 class="sml-txt card-title">Issue {{forloop.revcounter}}: {{issue.title}}</h5>
                            </div>
                        </a>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>

        <div style="margin:0; padding:0;" class="col-sm-4">
            <div class="info-box issue-box sticky-top d-flex">
                <div class="issue-header">
                    <div>
                        {{this.title}}<br />
                        {{thisIssue.title}}<br />
                        <div style="margin:0 !important;" class="sml-txt gry-txt">
                            {% for hashtag in this.hashtag_set.all %}
                            {{ hashtag }} &#160
                            {% endfor %}
                        </div>
                        {% if user.is_authenticated %}
                        <form class="save_issue" action="" method="POST" id="{{thisIssue.slug}}">
                            {% csrf_token %}
                            <button type="button" value="{{thisIssue.slug}}" class="btn btn-outline-secondary btn-sm favourite mt-2" onclick="saveIssue()">
                                Add to My Magazines
                            </button>
                        </form>
                        {% endif %}
                    </div>
                </div>

                <div class="issue-body">
                    <div class="sml-txt">
                        {{thisIssue.issue_description}}
                    </div>
                </div>

                <div class="issue-buy">
                    <div>
                        {% if subscribed %}
                            <a href="{{this.link_to_publishers_site}}" onclick="alert('Please remember to use your subscriber discount code at the checkout!')" type="button" class="btn btn-primary btn-sm pay">Subscriber Price &#163 {{thisIssue.discounted_price}}</a>
                            <a href="{{this.link_to_publishers_site}}" type="button" class="btn btn-outline-secondary btn-sm pay disabled"><strike>Full Price &#163 {{thisIssue.price}}</strike></a>
                        {% else %}
                            <a href="{% url 'home:membership' %}" type="button" class="btn btn-primary btn-sm pay">Subscriber Price &#163 {{thisIssue.discounted_price}}</a>
                            <a href="{{this.link_to_publishers_site}}" type="button" class="btn btn-outline-secondary btn-sm pay">Full Price &#163 {{thisIssue.price}}</a>
                        {% endif %}
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block script %}
<script>
    if (window.location.href.slice(-10) != "#Magazines") {
        window.location.href += "#Magazines";
    }
</script>

<script>
    var savedIss = []

    {% for iss in saved_issues %}
    savedIss.push("{{ iss.slug }}");
    {% endfor %}
</script>

<script src="{% static 'scripts/home.js' %}" defer></script>
<script src="{% static 'scripts/saveIssue.js' %}" defer></script>
{% endblock %}

templates/loginform.html
<!DOCTYPE html>

<div class="info-box py-0 px-0 mr-0 d-inline">
			<div class="card-body center">

			<center>
			<h3 class="card-title">Log In</h3>

			<div class="container sml-txt mt-3 d-inline">

			<form id="login_form" method="post" action="{%url 'home:login' %}">
				{% csrf_token %}



				<input type="username" name="username" placeholder="Username" required /><br></br>
				<input type="password" name="password" placeholder="Password" required/><br></br>
				 </div>
				 <div class="sml-txt">
				<input type="submit" value="Enter"/><br>
				</div>
				<a class = "sml-txt" href="{% url 'home:password_reset' %}">Forgot Password?</a>


			</form>
			<div class="info sml-txt">

				<div style="display: inline-block"><p>Don't have an account?</p></div>
			<a href="{% url 'home:signup' %}">Sign Up</a>
			</center>
			</div>
			</div>


</div>

templates/magazine.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="/static/styles/home.css">
{% endblock %}

{% block title %}
{{this.title}}
{% endblock %}

<!--see navbar.html for navbar code-->
{% block navbar %}
{% include "navbar.html" %}
{% endblock %}

{% block content %}
<div class="container py-0 px-0 mr-0 d-inline">
    <div class="row">
        <div style="min-height: 80vh;" class="col-sm-4 pt-3 px-0">
            {% include "sidebar.html" %}
        </div>

        <div class="col-sm-4 border-start border-end border-dark border-1 d-flex" id="mainbox">
            <div class="info-box sticky-top mx-4 pe-4 d-flex">
                <div class="issues mt-4">
                    {% for issue in issues reversed %}
                        <a href="{% url 'home:issue' this.id issue.slug %}" class="issue-crd card issue-link py-1">
                            <img class="card-img-top" src="{{ issue.cover.url }}" />
                            <div style=" display:flex; justify-content:center;" class="card-body">
                                <h5 class="sml-txt card-title">Issue {{forloop.revcounter}}: {{issue.title}}</h5>
                            </div>
                        </a>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="col-sm-4 d-flex" id="mainbox">
            <div class="info-box sticky-top px-4 py-4 d-flex">
                About {{this.title}}

                <div class="info sml-txt mt-3 d-inline">
                    {{this.description_long}}
                </div>
            </div>
            
        </div>
    </div>
</div>

{% endblock %}

{% block script %}
<script>
    if (window.location.href.slice(-10) != "#Magazines") {
        window.location.href += "#Magazines";
    }
</script>

<script src="{% static 'scripts/home.js' %}" defer></script>
{% endblock %}	

templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="/static/styles/login.css">
{% endblock %}
{% block title %}
Sign Up
{% endblock %}

<!--see navbar.html for navbar code-->
{% block navbar %}
{% include "navbar.html" %}
{% endblock %}

{% block content %}

    <div id="signup_form" class="info-box py-0 px-0 mr-0 d-inline">
			
			<div class="card-body center">
			<center>
			{% if registered %}
			<p>Thank you for registering!</p>
			<a href="{% url 'home:home' %}">Return to homepage.</a>
			
			{% else %}
			<h3 class="card-title">Sign Up</h3>
			
			
			
			<div class="container sml-txt mt-3 d-inline">
			<form  method="post" action="{%url 'home:signup' %}" >
				{% csrf_token %}
				
				
					<input type="email" name="email" placeholder="Email" required/>

					<p>{{ form.email.errors.as_text }}</p>
					
						
					
					<input type="username" name="username" placeholder="Username" required/>
					
					<p>{{ form.username.errors.as_text }}</p>
					
					
					<input type="password" name="password" placeholder="Password" required />				
					
					<p>{{ form.password.errors.as_text }}</p>
					
				
					
					<input type="password" name="confirm_password" placeholder="Repeat Password" required />
					
					<p>{{ form.confirm_password.errors.as_text }}</p>
					
					



				
				
				<div class="info xsml-txt gry-txt">
				<input type="checkbox" id="terms" required onchange="this.setCustomValidity(validity.valueMissing ? 'Please accept the Terms and Conditions of use to continue.' : '');" />
				<p>I accept the Terms and Conditions of use.</p>
				
				
				
				</div>
				
				<div class="info sml-txt ">
				<input type="submit" name="submit" value="Enter" href="{% url 'home:login' %}" />

				</div>
			</center>
			</form>
			
			
			
			{% endif %}
			</div>
			
			
</div>
</div>
<script src="{% static 'scripts/signup.js' %}"></script>	
{% endblock %}

templates/staff.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="/static/styles/home.css">
<link rel="stylesheet" type="text/css" href="/static/styles/staff.css">
{% endblock %}

{% block title %}
Staff Portal
{% endblock %}

<!--see navbar.html for navbar code-->
{% block navbar %}
{% include "navbar.html" %}
{% endblock %}

{% block content %}
<div class="container py-0 px-0 mr-0 d-inline">
    <div class="row">
        <div style="min-height: 80vh;" class="col-sm-4 pt-3 px-0">
            {% include "sidebar.html" %}
        </div>

        <div class="col-sm-4 border-start border-end border-dark border-1 d-flex" id="mainbox">
            <div class="info-box sticky-top mx-4 pe-4 d-flex align-items-center">
                <h1 class="mt-5 mb-3">
                    <u>Staff Portal</u>
                </h1>

                <ul class="mt-4">
                    <li>
                        <a href="/admin/" class="issue-link">
                            Visit administrator panel to view and update database
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'home:codes' %}" class="issue-link">
                            Generate discount codes.
                        </a>
                    </li>
                </ul>
            </div>
        </div>

    </div>
</div>
{% endblock %}