boom_saloon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import include, path, reverse_lazy
from home import views
from django.contrib.auth import views as auth_views



app_name = 'home'

urlpatterns = [
    path('', views.home, name="home"),
    path('login/', views.user_login, name="login"),
    path('myprofile/', views.my_profile, name="myprofile"),
    path('signup/', views.user_signup, name="signup"),
    path('<int:id>/', views.magazine, name="magazine"),
    path('<int:id>/<slug:slug>/', views.issue, name="issue"),
    path('contact/', views.contact, name="contact"),
    path('mymagazines/', views.mymags, name="mymagazines"),
    path('signout/', views.user_signout, name="signout"),
    path('saveissue/', views.save_issue, name="save-issue"),
    path('membership/', views.membership, name="membership"),
    path('staff/', views.staff, name="staff"),
    path('codes/', views.codes, name='codes'),
    path('password_reset/done/', views.password_reset_done, name='password_reset_done'),
    path("password_reset", views.password_reset_request, name="password_reset"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="resetpassword/password_reset_confirm.html", success_url=reverse_lazy(
        'home:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', views.password_reset_complete, name='password_reset_complete'),
    path('email/', views.send_code, name="sendcode"),
    path('payment-done/', views.payment_done, name='payment_done'),
    path('payment-cancelled/', views.payment_cancelled, name='payment_cancelled'),
    path('confirm_email/<uidb64>/<token>/', views.confirm_email, name='activate'),
    path('verify_email/', views.send_confirmation_email, name="sendvemail"),

]

home/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.core.validators import MinLengthValidator
from django.contrib.auth.models import User
import datetime
import dateutil.relativedelta as dt



class Magazine(models.Model):

    id = models.IntegerField(unique=True, primary_key=True)
    title = models.CharField(max_length=100, unique=True)
    description_short = models.CharField(max_length=1000)
    #long - in case we have seperate pages for each magzine
    description_long = models.CharField(max_length=2000)
    link_to_publishers_site = models.URLField(max_length=300)
    #slug - again, in case we have seperate pages for each magzine
    slug = models.SlugField(unique=True)
    mag_cover = models.ImageField(upload_to='mag_covers', default=None)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Magazine, self).save(*args, **kwargs)


class MagazineIssue (models.Model):
    magazine = models.ForeignKey(Magazine, on_delete=models.CASCADE)
    title = models.CharField(max_length =1000, default="No title", unique=True)
    issue_description = models.CharField(max_length=1000)
    price = models.IntegerField(default = 0 )
    discounted_price = models.IntegerField(default= 0)
    cover = models.ImageField(upload_to='issue_covers', default=None)
    description_short = models.CharField(max_length=1000, default=None, null=True)
    date = models.DateField(("Date"), default=datetime.date.today)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(MagazineIssue, self).save(*args, **kwargs)


class UserProfile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    saved_issues = models.ManyToManyField(MagazineIssue, related_name="saves")
    is_subscribed = models.BooleanField(default=False)
    has_code = models.BooleanField(default=False)
    date_subscribed =  models.DateField(("Date"), default=datetime.date.today)
    email_confirmed = models.BooleanField(default=False)


    def __str__(self):
        return self.user.username


class Hashtag(models.Model):
    text = models.CharField(max_length=20)
    magazines = models.ManyToManyField(Magazine)

    def __str__(self):
        return self.text


class DiscountCode(models.Model):
    code = models.CharField(max_length=16, validators=[MinLengthValidator(16)])
    date_valid=models.DateTimeField(("Date"),default=datetime.date.today()+dt.relativedelta(months=1))
    def __str__(self):
        return self.code
        
class Membership(models.Model):
	user=models.OneToOneField(User, on_delete=models.CASCADE)
	date_subscribed= models.DateField(("Date"),default=datetime.date.today)
	date_valid=models.DateField(("Date"))
	code=models.CharField(max_length=16, validators=[MinLengthValidator(16)])

templates/mobiletemplates/allmagazinesmobile.html
<!DOCTYPE html>

{% load static %}

<div id="allmagazineswrapper">


      <div>
          <input type="text" id="searchBar" onkeyup="searchBarFunction()" placeholder="search magazines or topics">
      </div>
     {% for magazine in magazines %}
         <div class="mag_list_element_wrap">

         <a class="magazine_or_issue_list_link" href="{% url 'home:magazine' magazine.id %}">

            <div class="mag_list_element">
                <img class="mag_list_cover_image" src="{{ magazine.mag_cover.url }}" />


                <div class="mag_list_text all_mags">

                       <span> {{ magazine.title }} </span>


                    <div class="hashtags">
                        {% for hashtag in magazine.hashtag_set.all %}
                        <hashtag> {{ hashtag }}, &#160 </hashtag>
                        {% endfor %}
                    </div>
                </div>



            </div>
          </a>
            <div class="mag_list_line"></div>
         </div>
    {% endfor %}

</div>

<script src="{% static 'scripts/searchbarmobile.js' %}"></script>

templates/mobiletemplates/basemobile.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">

	<!-- Bootstrap CSS -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

	<!-- link to style.css  -->
	<link rel="stylesheet" type="text/css" href="/static/styles/style.css">
	<!--loop icon library-->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<!--Arizona font-->
	<link href="{% static 'fonts/ABC-Arizona-Text/ABCArizonaText-Regular-Trial.otf' %}" rel="stylesheet" media="screen">

	<link rel="shortcut icon" href="/static/icon/favicon-32x32.png" sizes="32x32" type="image/png">

	<!--Custiom CSS-->
    {#<link rel="stylesheet" type="text/css" href="/static/styles/home.css">#}
    <link rel="stylesheet" type="text/css" href="/static/styles/mobile.css">



	<title>
		CLO -
		{% block title %}
		{% endblock %}
	</title>

</head>

<body>

<div id="mainwrapper">
   <div id="logo-bar">
       <a  href="/">
            <img id="logo-image" src="{% static 'logos/clo-wordmark-blue.png' %}" />
       </a>
   </div>


    {% block content %}
    {% endblock %}

</div>
    <!-- Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

	{% block script %}
    {% endblock %}
</body>

</html>

templates/mobiletemplates/emailverifyfailmobile.html
<!DOCTYPE html>
{% extends 'mobiletemplates/basemobile.html' %}
{% load static %}

{% block title %}
    Email-verify-fail-mobile
{% endblock %}

{% block content %}

	<div class="container p-5">
  	 	<h2 class="font-weight-bold mt-3">Email Verification Link Error</h2>

		<p>This link may be invalid/expired, please request a new one using the login tab.</p>
        <a class="basic_link" href="{% url 'home:home' %}">Login</a>

  	</div>

{% endblock %}

templates/mobiletemplates/emailverifysuccessmobile.html
<!DOCTYPE html>
{% extends 'mobiletemplates/basemobile.html' %}
{% load static %}

{% block title %}
    Email-verify-success-mobile
{% endblock %}

{% block content %}

    <div class="container p-5">
  	 	<h2 class="font-weight-bold mt-3">Email Verified</h2>

        <p>You have successfully verified your Clò email.</p>
        <a class="basic_link" href="{% url 'home:home' %}"> Login </a>

  	</div>

{% endblock %}

templates/mobiletemplates/homemobile.html
{% extends 'mobiletemplates/basemobile.html' %}
{% load static %}




{% block title %}
Home - Mobile
{% endblock %}



{% block content %}


    <div id="aboutclo">
        <p>
            <h4>
                About Cl&ograve
            </h4>
        </p>

        <p>
            lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
            ut labore et dolore magna aliqua. ut enim ad minim veniam, quis nostrud exercitation ullamco
            laboris nisi ut aliquip ex ea commodo consequat.
            duis aute irure dolor in reprehenderit in voluptate
            velit esse cillum dolore eu fugiat nulla pariatur. excepteur sint occaecat cupidatat non proident, sunt
            in culpa qui officia deserunt mollit anim id est laborum.

        </p>

    </div>


    <div class="menuwrapper">

        <div class="menuelement">
            <img class="closeicondummy" src="{% static 'icon/close.svg' %}"> {% comment %}This will not be visible -
            inserted here for ease of styling with justify-content: space between of the menuelement - to ensure
            that the "all magazine" text is always in the centre and the closeicon always close to the right edge of
            the screen on devices of all dimension - a trick to compensate for the lack of justify-self css property
            for justifying corresponding to align-self for aligning{% endcomment %}
            <a > All Magazines </a>
            <img class="closeicon" src="{% static 'icon/close.svg' %}">

        </div>

        <div class="hiddenpanel">
            {% include "mobiletemplates/allmagazinesmobile.html" %}
        </div>

    {% if user.is_authenticated %}
        <div class="menuelement" id="membership_authenticated">
            <img class="closeicondummy" src="{% static 'icon/close.svg' %}">
            <a> Membership </a>
            <img class="closeicon" src="{% static 'icon/close.svg' %}">
        </div>
    {% else %}
        <div class="menuelement" id="membership_not_authenticated">
            <img class="closeicondummy" src="{% static 'icon/close.svg' %}">
            <a> Membership </a>
            <img class="closeicon" src="{% static 'icon/close.svg' %}">
        </div>
    {% endif %}

        <div class="hiddenpanel" id="membership_outer_hidden_panel">
            <p><a class="basic_link" href="{% url 'home:myprofile' %}">Go to Membership Menu</a></p>
        </div>

        <div class="menuelement">
             <img class="closeicondummy" src="{% static 'icon/close.svg' %}">
             <a> Contact </a>
             <img class="closeicon" src="{% static 'icon/close.svg' %}">
        </div>

        <div class="hiddenpanel">
            {% include "mobiletemplates/contactmobile.html" %}
        </div>

        <div id="login_element" class="menuelement">
            {% if user.is_authenticated %}
                    <img class="closeicondummy" src="{% static 'icon/close.svg' %}">
                    <a>Sign Out</a>
                    <img class="closeicon" src="{% static 'icon/close.svg' %}">
            {% else %}
                    <img class="closeicondummy" id="closelogin" src="{% static 'icon/close.svg' %}">
                    <a>Log In</a>
                    <img class="closeicon" src="{% static 'icon/close.svg' %}">
            {% endif %}

        </div>

    {% if not user.is_authenticated %}
        <div class="hiddenpanel">
           {% include "mobiletemplates/loginmobile.html" %}
        </div>
    {% else %}
        <div class="hiddenpanel">
            <p>Are you sure you want to sign out?</p>
            <p><a class="basic_link" href="{% url 'home:signout' %}">Yes</a></p>

        </div>
    {% endif %}

    </div>



{% endblock %}







{% block script %}
    <script src="{% static 'scripts/home.js' %}"></script>
    <script src="{% static 'scripts/homemobile.js' %}"></script>
{% endblock %}

templates/mobiletemplates/issuemobile.html
{% extends 'mobiletemplates/basemobile.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="/static/styles/home.css">
<link rel="stylesheet" type="text/css" href="/static/styles/mobile.css">
{% endblock %}

{% block title %}
{{this.title}}
{% endblock %}


{% block content %}

    <img class="cover_image" src="{{ thisIssue.cover.url }}" />

    <div class="issue_title_block">
        <div class="issue_title_text">
            <div> {{ this.title }}</div>
            <div id="issue_title"> {{ thisIssue.title }}</div>
        </div>

        {% if user.is_authenticated %}
        <form class="save_issue" action="" method="POST" id="{{thisIssue.slug}}">
            {% csrf_token %}
            <button type="button" class="favourite_mobile favourite" value="{{thisIssue.slug}}"  onclick="saveIssue()">
                Add to My Magazines
            </button>
        </form>
        {% endif %}
    </div>

    <div class="mag_and_issue_line"></div>

    <div class="mag_or_issue_wrap">

        <div class="hashtags">
            {% for hashtag in this.hashtag_set.all %}
            {{ hashtag }}, &#160
            {% endfor %}
        </div>

        <div class="mag_and_issue_description">
            <p>{{ thisIssue.issue_description }}</p>
        </div>

        <div class="buy_buttons">
            {% if subscribed %}
                <a href="{{this.link_to_publishers_site}}" onclick="alert('Please go to the Membership area to' +
                 ' recieve your subscriber code if you have not already')" type="button" class="left_button" >
                    Subscriber Price &#163
                    {{thisIssue.discounted_price}}</a>

                <a href="{{this.link_to_publishers_site}}" type="button" class="right_button">
                    <strike>Full Price &#163 {{thisIssue.price}}</strike></a>

            {% else %}
                <a href="{% url 'home:myprofile' %}" type="button" class="left_button" >
                    Subscriber Price &#163 {{thisIssue.discounted_price}}</a>
                <a href="{{this.link_to_publishers_site}}" type="button" class="right_button">
                    Full Price &#163 {{thisIssue.price}}</a>
            {% endif %}
        </div>
    </div>

    <div id="issue_back_button" class="backbutton">
        <a id="issue_back_button_text" class="basic_link" href="{% url 'home:magazine' this.id %}">Back to Magazine</a>
    </div>


{% endblock %}




{% block script %}
<script>
    if (window.location.href.slice(-10) != "#Magazines") {
        window.location.href += "#Magazines";
    }
</script>

<script>
    var savedIss = []

    {% for iss in saved_issues %}
    savedIss.push("{{ iss.slug }}");
    {% endfor %}
</script>

<script src="{% static 'scripts/home.js' %}" defer></script>
<script src="{% static 'scripts/saveIssue.js' %}" defer></script>
{% endblock %}

templates/mobiletemplates/magazinemobile.html
{% extends 'mobiletemplates/basemobile.html' %}
{% load static %}



{% block title %}
{{this.title}}
{% endblock %}


{% block content %}



    <img class="cover_image" src="{{ latest_issue.cover.url }}" />

    <div id="magazine_title">
        {{ this.title }}
    </div>



    <div class="mag_and_issue_line"></div>

    <div id="magazine_wrap" class="mag_or_issue_wrap">
        <div class="hashtags">
            {% for hashtag in this.hashtag_set.all %}
            {{ hashtag }}, &#160
            {% endfor %}
        </div>

        <div class="mag_and_issue_description">
            <p>{{ this.description_short }}</p>

{#            Magazine's website:#}
{#            <a> {{ this.link_to_publishers_site }} </a>#}

        </div>
        <div id="latest_issue">
            <p>Latest Issue:</p>
            <a href="{% url 'home:issue' this.id latest_issue.slug %}" class="basic_link">
               {{ latest_issue.title }}
            </a>
        </div>

        <div class="buy_buttons">
            {% if subscribed %}
                <a href="{{this.link_to_publishers_site}}" onclick="alert('Please go to the Membership area to' +
                 ' recieve your subscriber code if you have not already')" type="button" class="left_button" >
                    Subscriber Price &#163
                    {{latest_issue.discounted_price}}</a>

                <a href="{{this.link_to_publishers_site}}" type="button" class="right_button">
                    <strike>Full Price &#163 {{latest_issue.price}}</strike></a>

            {% else %}
                <a href="{% url 'home:myprofile' %}" type="button" class="left_button" >
                    Subscriber Price &#163 {{latest_issue.discounted_price}}</a>
                <a href="{{this.link_to_publishers_site}}" type="button" class="right_button">
                    Full Price &#163 {{latest_issue.price}}</a>
            {% endif %}
        </div>
    </div>

    <div id="magazine_menu_wrap">
        <div class="menuelement " id="magazine_menu_element" >
            <img class="closeicondummy" src="{% static 'icon/close.svg' %}">
            <a> All Issues </a>
            <img class="closeicon" src="{% static 'icon/close.svg' %}">

        </div>

        <div id="hidden_panel_issues">

            {% for issue in issues %}
                <a class="magazine_or_issue_list_link" href="{% url 'home:issue' this.id issue.slug %} ">
                <div class="mag_list_element">
                    <img class="mag_list_cover_image" src="{{ issue.cover.url }}" />

                    <div class="mag_list_text">

                            {{ issue.title }}


                        <div class="issue_date">Published: {{ issue.date|date:"j M y" }}</div>
                    </div>



                </div>
                 </a>
                <div class="mag_list_line"></div>
            {% endfor %}

        </div>
    </div>


{% endblock %}

{% block script %}
<script>
    if (window.location.href.slice(-10) != "#Magazines") {
        window.location.href += "#Magazines";
    }
</script>

    <script src="{% static 'scripts/home.js' %}"></script>
    <script src="{% static 'scripts/magazinemobile.js' %}"></script>

    <script src="{% static 'scripts/home.js' %}" defer></script>
{% endblock %}

templates/mobiletemplates/membershipmenumobile.html
{% extends 'mobiletemplates/basemobile.html' %}
{% load static %}

{% block title %}
    Sign up
{% endblock %}

{% block content %}

<div class="menuwrapper">



    <div id="membershipinfo">
        <p>
{#            Break instead of using padding or margin in the css file because - the max-height property doesn't include #}
{#            them - faulty accordion menu#}
            <br>
            Check you account details, your subscription or view your saved magazine issues below.
            <br>
        </p>
    </div>

    <div class="menuelement">
        <img class="closeicondummy" src="{% static 'icon/close.svg' %}">
        <a > My Profile </a>
        <img class="closeicon" src="{% static 'icon/close.svg' %}">

    </div>

    <div class="hiddenpanel">
        <div> {% include "mobiletemplates/myprofilemobile.html" %}</div>
    </div>


    <div class="menuelement">
        <img class="closeicondummy" src="{% static 'icon/close.svg' %}">
            <a > My Subscription </a>
        <img class="closeicon" src="{% static 'icon/close.svg' %}">

    </div>

    <div class="hiddenpanel">
        <div> {% include "mobiletemplates/mysubscriptionmobile.html" %}</div>
    </div>


    <div class="menuelement">
        <img class="closeicondummy" src="{% static 'icon/close.svg' %}">
        <a > My Magazines </a>
        <img class="closeicon" src="{% static 'icon/close.svg' %}">

    </div>

    <div class="hiddenpanel">
        <div>{% include "mobiletemplates/mymagazinesmobile.html" %}</div>
    </div>

    <div class="backbutton">
        <a class="basic_link" href="{% url 'home:home' %}">Back</a>
    </div>

</div>

{% endblock %}

{% block script %}
    <script src="{% static 'scripts/home.js' %}"></script>
    <script src="{% static 'scripts/membershipmobile.js' %}"></script>
{% endblock %}

templates/mobiletemplates/mymagazinesmobile.html
<!DOCTYPE html>

<div id="my_magazines_wrap">
                {% if savedissues %}
                {% for issue in savedissues %}
                <div class="saved-box">
                    <a href="{% url 'home:issue' issue.magazine.id issue.slug %}" class="saved-link basic_link">
                        {{issue.magazine.title}} - {{issue.title}}
                    </a>
                </div>
                {% endfor %}
                {% else %}
                <div class="saved-box">
                    You haven't saved any magazines yet!
                </div>
                {% endif %}


</div>

templates/mobiletemplates/password_reset_complete_mobile.html
<!DOCTYPE html>
{% extends 'mobiletemplates/basemobile.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="/static/styles/home.css">
{% endblock %}

{% block title %}
Reset Password - Complete
{% endblock %}



{% block content %}

<!--Password Reset Complete-->
    <div class="text-center container p-4">
	    <h2 class="font-weight-bold mt-3">Password reset complete</h2>

        <p>Your password has been set. You may go ahead and log in now.</p>
        <a href="/login" class="basic_link ">Log in</a>
    </div>

{% endblock %}

templates/mobiletemplates/password_reset_confirm_mobile.html
<!DOCTYPE html>
{% extends 'mobiletemplates/basemobile.html' %}
{% load static %}
{% load myfilter %}

{% block css %}
<link rel="stylesheet" type="text/css" href="/static/styles/home.css">
{% endblock %}

{% block title %}
Reset Password - New Password
{% endblock %}


{% block content %}

<!--Password Reset Confirm-->
    <div class="container p-5">
	    <h2 style="font-weight: bold" class=" mt-3">Password Reset</h2>

        <p>Please enter your new password.</p>
        <form style="text-align: center" method="POST">
            {% csrf_token %}
            {{form.non_field_errors}}
            {% for field in form %}
                {{field.label_tag}}
                {{ field | addclass:'form-control'}}
                {% if field.errors %}
                    <div style="color: red">
                    {{ field.errors }}
                    </div>
                {% endif %}
                {% endfor %}
            <br>
            <button class="btn btn-primary" type="submit">Reset</button>
        </form>
    </div>

{% endblock %}

templates/mobiletemplates/payment_cancelled_mobile.html
<!DOCTYPE html>
{% extends 'mobiletemplates/basemobile.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="/static/styles/home.css">
{% endblock %}

{% block title %}
Payment Cancelled - mobile
{% endblock %}



{% block content %}


<div id="payment_cancelled">
    <div >
        	<div>
    <p>Payment was cancelled.</p>
    <a class="basic_link" href="{% url 'home:home' %}"> Return to homepage.</a>
    </div>
    </div>
    </div>

{% endblock %}

templates/mobiletemplates/payment_done_mobile.html
<!DOCTYPE html>
<!DOCTYPE html>
{% extends 'mobiletemplates/basemobile.html' %}
{% load static %}
{% load myfilter %}

{% block css %}
<link rel="stylesheet" type="text/css" href="/static/styles/home.css"><link rel="stylesheet" type="text/css" href="/static/styles/membership.css">
{% endblock %}

{% block title %}
Payment Done - Mobile
{% endblock %}


{% block content %}


<div style="margin-left: 1em; margin-right: 1em; text-align: center">
    <div >
        	<div style="margin-top:2em;">
    <p>Payment was successful. Your discount code will be emailed to you.</p>
    <a class="basic_link" href="{% url 'home:home' %}"> Return to homepage.</a>
    </div>
    </div>
    </div>


{% endblock %}

templates/mobiletemplates/signupmobile.html
{% extends 'mobiletemplates/basemobile.html' %}
{% load static %}

{% block title %}
    Sign up
{% endblock %}

{% block content %}

<div class="basic_form">

			{% if registered %}
			<p>Thank you for registering!</p>
			<a href="{% url 'home:home' %}">Return to homepage.</a>

			{% else %}
			<h3 class="card-title">Sign Up</h3>




			<form id=signup_form" method="post" action="{%url 'home:signup' %}" >
				{% csrf_token %}


					<input type="email" name="email" placeholder="Email" required/>

					<p>{{ form.username.errors.as_text }}</p>



					<input type="username" name="username" placeholder="Username" required/>

					<p>{{ form.username.errors.as_text }}</p>


					<input type="password" name="password" placeholder="Password" required />

					<p>{{ form.password.errors.as_text }}</p>



					<input type="password" name="confirm_password" placeholder="Repeat Password" required />

					<p>{{ form.confirm_password.errors.as_text }}</p>





				<div class="info xsml-txt gry-txt">
				<input type="checkbox" id="terms" required onchange="this.setCustomValidity(validity.valueMissing ?
				 'Please accept the Terms and Conditions of use to continue.' : '');" />
				<p>I accept the Terms and Conditions of use.</p>



				</div>

				<div class="info sml-txt ">
				    <input type="submit" name="submit" value="Enter" href="{% url 'home:login' %}" />
                </div>

			</form>



			{% endif %}

<script src="{% static 'scripts/signup.js' %}"></script>

</div>

{% endblock %}